name: LeanCloud Query

on:
  push:
    branches:
      - main

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
          echo "Inputs: ${{ toJson(github.event.inputs) }}"
